#### Pedro Freitas
#### Prueba tecnica - Tekal
#### NLP problem - Dataset generation

In [1]:
import pandas as pd

from utils.preproc import *

client_secret.json-drive-v3-(['https://www.googleapis.com/auth/drive'],)
['https://www.googleapis.com/auth/drive']
drive service created successfully

## Import dataset

In [2]:
# import dataset
df = pd.read_csv('set_de_datos_con_perspectiva_de_genero - set_de_datos_unificado.csv')
df = df[0:3411] #only 3411 rows with data
df

,N,NRO_REGISTRO,FECHA_RESOLUCION,FIRMA,MATERIA,ART_INFRINGIDO,CODIGO_O_LEY,CONDUCTA,CONDUCTA_DESCRIPCION,VIOLENCIA_DE_GENERO,...,DECISION_DE_ADMISIBILIDAD_TSJ,N_REGISTRO_Y_TOMO_CAMARA_2,LINK_CAMARA_2,DECISION_DE_FONDO_TSJ,N_REGISTRO_Y_TOMO_TSJ,LINK_TSJ,RECURSO_EXTRAORDINARIO_Y_RECURRENTE,DECISION_CSJN,N_REGISTRO_Y_TOMO_CSJN,LINK_CSJN
0,1.0,NaN,1_8_2016,Pablo_Casas,penal,1,ley_14346,proteccion_animal,simples,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,NaN,1_8_2016,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,si,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,NaN,2_8_2016,Pablo_Casas,contravencional,52,codigo_contravencional,hostigamiento,agravado_violencia_de_genero,si,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,NaN,2_8_2016,Pablo_Casas,contravencional,73,codigo_contravencional,incumplir_clausura,NaN,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,NaN,2_8_2016,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,si,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3406,2783.0,2890,7_08_20,Pablo_Casas,penal,189bis,codigo_penal_de_la_nacion,tenencia_de_arma,de_fuego_uso_civil,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3407,2784.0,2891,8_08_20,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3408,NaN,2891,8_08_20,Pablo_Casas,penal,183,codigo_penal_de_la_nacion,daños,NaN,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3409,NaN,2891,8_08_20,Pablo_Casas,penal,186_inc1,codigo_penal_de_la_nacion,incendio_explosion_inundacion_con_peligro_para...,NaN,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3410,2785.0,2892,9_08_20,Pablo_Casas,penal,239,codigo_penal_de_la_nacion,desobediencia_a_la_autoridad,NaN,si,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# fill missing values for N with previous value
df['N'].fillna(method='ffill', inplace=True)

# remove rows with missing links as the docs are the feature of our model
df = df[~df.LINK.isnull()]
df.shape

(3393, 61)

## Download docs, extract texts, and save to csv

In [4]:
# extract google drive ids from links
ids = [get_id(url) for url in df['LINK']]

In [5]:
# extract text given id
texts = []
i = 0
for doc_id in ids:
    print(i)
    try:
        text = get_text2(doc_id) #download doc file and extract its text
        text = text.decode('utf-8')
    except:
        text = None
        print('Download failed')
        
    texts.append(text)
    i = i+1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
Download failed
242
Download failed
243
244
245
246
247
248
249
250
251
Download failed
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
Download failed
500
501
502
503
504
505
Download failed
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
Download failed
544
545
546
547
Download failed
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
Download failed
644
Download failed
645
Download failed
646
647
Download failed
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
Download failed
663
664
665
666
667
668
669
670
Download failed
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
Download failed
694
Download failed
695
696
Download failed
697
Download failed
698
Download failed
699
Download failed
700
701
702
703
704
Download failed
705
706
707
Download failed
708
709
710
711
712
713
714
715
716
717
718
719
Download failed
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
Download failed
765
766
767
768
769
770
771
Download failed
772
773
774
775
776
777
778
Download failed
779
780
781
782
783
784
Download failed
785
Download failed
786
787
788
789
790
791
792
793
794
795
796
797
798
Download failed
799
Download failed
800
Download failed
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
Download failed
838
839
Download failed
840
841
842
843
844
845
846
Download failed
847
Download failed
848
Download failed
849
850
Download failed
851
Download failed
852
Download failed
853
Download failed
854
Download failed
855
Download failed
856
Download failed
857
858
859
Download failed
860
Download failed
861
Download failed
862
863
Download failed
864
Download failed
865
Download failed
866
Download failed
867
868
Download failed
869
Download failed
870
Download failed
871
Download failed
872
873
874
Download failed
875
876
877
Download failed
878
879
880
881
Download failed
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
Download failed
899
900
Download failed
901
902
Download failed
903
904
Download failed
905
906
Download failed
907
908
Download failed
909
910
Download failed
911
912
Download failed
913
914
915
916
917
Download failed
918
919
Download failed
920
921
Download failed
922
923
924
925
926
927
928
929
930
Download failed
931
932
Download failed
933
934
Download failed
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
Download failed
1169
Download failed
1170
Download failed
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626

1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265

3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392

In [ ]:
# add ids and texts to df
df.loc[:,'DOCS_ID'] = ids
df.loc[:,'TEXTOS'] = texts

In [16]:
df.shape

(3393, 63)

In [17]:
# missing texts. 
df.TEXTOS.isnull().sum()

73

In [7]:
# save df generated to csv to be used in the steps
df.to_csv('df_raw_text2.csv')

## EDA of selected variables

In [21]:
df = pd.read_csv('df_raw_text2.csv')
df

,Unnamed: 0,N,NRO_REGISTRO,FECHA_RESOLUCION,FIRMA,MATERIA,ART_INFRINGIDO,CODIGO_O_LEY,CONDUCTA,CONDUCTA_DESCRIPCION,...,LINK_CAMARA_2,DECISION_DE_FONDO_TSJ,N_REGISTRO_Y_TOMO_TSJ,LINK_TSJ,RECURSO_EXTRAORDINARIO_Y_RECURRENTE,DECISION_CSJN,N_REGISTRO_Y_TOMO_CSJN,LINK_CSJN,DOCS_ID,TEXTOS
0,0,1.0,NaN,1_8_2016,Pablo_Casas,penal,1,ley_14346,proteccion_animal,simples,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0B9wNhp3GjjazTVhZM2dCRU1IN2M,'U\n\n� Poder Judicial de la Ciudad de Buenos ...
1,1,2.0,NaN,1_8_2016,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0B9wNhp3GjjazTjRHVHl2YzBtUEU,� Poder Judicial de la Ciudad de Buenos Aires\...
2,2,3.0,NaN,2_8_2016,Pablo_Casas,contravencional,52,codigo_contravencional,hostigamiento,agravado_violencia_de_genero,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0B9wNhp3GjjazY3VCak5kdTBvWWc,'o\n·\n\nPoder Judicial de la Ciudad de Buenos...
3,3,4.0,NaN,2_8_2016,Pablo_Casas,contravencional,73,codigo_contravencional,incumplir_clausura,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0B9wNhp3Gjjazc2V4eWVaeWVRQUE,� Poder Judicial de la Ciudad de Buenos Aires\...
4,4,5.0,NaN,2_8_2016,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0B9wNhp3GjjazZFdmVXlWbFdYSHc,"""\n\n_.¡\n\n�s\n�li.2l!l\n\n� Poder Judicial d..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,3396,2775.0,"2883,1",6_08_20,Pablo_Casas,penal,92,codigo_penal_de_la_nacion,lesiones,leves_agravadas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10H4NjKb9BhjUrCfzwTankVay6AGqrHj7,RESOLUCIÓN INTERLOCUTORIA\nHace lugar a las me...
3389,3407,2784.0,2891,8_08_20,Pablo_Casas,penal,149bis,codigo_penal_de_la_nacion,amenazas,simples,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Zht2hB79c-c5dVS-GoSwl95RpduzyMX5,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...
3390,3408,2784.0,2891,8_08_20,Pablo_Casas,penal,183,codigo_penal_de_la_nacion,daños,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Zht2hB79c-c5dVS-GoSwl95RpduzyMX5,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...
3391,3409,2784.0,2891,8_08_20,Pablo_Casas,penal,186_inc1,codigo_penal_de_la_nacion,incendio_explosion_inundacion_con_peligro_para...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1Zht2hB79c-c5dVS-GoSwl95RpduzyMX5,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...
3392,3410,2785.0,2892,9_08_20,Pablo_Casas,penal,239,codigo_penal_de_la_nacion,desobediencia_a_la_autoridad,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1w7qPcRIyqevAhzHRC3gGIsEDti4X10O2,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3393 entries, 0 to 3392
Data columns (total 64 columns):
Unnamed: 0                                             3393 non-null int64
N                                                      3393 non-null float64
NRO_REGISTRO                                           3240 non-null object
FECHA_RESOLUCION                                       3393 non-null object
FIRMA                                                  3393 non-null object
MATERIA                                                3393 non-null object
ART_INFRINGIDO                                         3373 non-null object
CODIGO_O_LEY                                           3373 non-null object
CONDUCTA                                               3393 non-null object
CONDUCTA_DESCRIPCION                                   1150 non-null object
VIOLENCIA_DE_GENERO                                    3393 non-null object
V_FISICA                                               3393 non-null object
V_PSIC                                                 3393 non-null object
V_ECON                                                 3393 non-null object
V_SEX                                                  3393 non-null object
V_SOC                                                  3393 non-null object
V_AMB                                                  3393 non-null object
V_SIMB                                                 3393 non-null object
FRASES_AGRESION                                        686 non-null object
GENERO_ACUSADO/A                                       3391 non-null object
NACIONALIDAD_ACUSADO/A                                 3387 non-null object
EDAD_ACUSADO/A AL MOMENTO DEL HECHO                    3386 non-null object
NIVEL_INSTRUCCION_ACUSADO/A                            3230 non-null object
GENERO_DENUNCIANTE                                     3385 non-null object
NACIONALIDAD_DENUNCIANTE                               3380 non-null object
EDAD_DENUNCIANTE_AL_MOMENTO_DEL_HECHO                  3381 non-null object
NIVEL_INSTRUCCION_DENUNCIANTE                          3380 non-null object
DOMICILIO_DENUNCIANTE                                  3381 non-null object
FRECUENCIA_EPISODIOS                                   3360 non-null object
RELACION_Y_TIPO_ENTRE_ACUSADO/A_Y_DENUNCIANTE          3363 non-null object
HIJOS/AS_EN_COMUN                                      3363 non-null object
MEDIDAS_DE_PROTECCION_VIGENTES_AL_MOMENTO_DEL_HECHO    3360 non-null object
ZONA_DEL_HECHO                                         3367 non-null object
LUGAR_DEL_HECHO
                                       3367 non-null object
TIPO_DE_RESOLUCION                                     3393 non-null object
OBJETO_DE_LA_RESOLUCION                                3393 non-null object
DETALLE                                                3095 non-null object
DECISION                                               3393 non-null object
ORAL_ESCRITA                                           3393 non-null object
HORA_DE_INICIO                                         1457 non-null object
HORA_DE_CIERRE                                         1432 non-null object
LINK                                                   3393 non-null object
DURACION                                               3386 non-null object
SI_NO_RECURRENTE                                       2003 non-null object
DECISION_CAMARA_DE_APELACIONES                         989 non-null object
N_REGISTRO_Y_TOMO_CAMARA                               989 non-null object
LINK_CAMARA                                            989 non-null object
SI_NO_RECURRENTE.1                                     975 non-null object
DECISION_DE_ADMISIBILIDAD_CAMARA                       953 non-null object
N_REGISTRO_Y_TOMO_CAMARA_1                             953 non-null object
LINK_CAMARA_1                                          953 non-null object
QUEJA_Y_RECURRENTE                                     939 non-null object
DECISION_DE_ADMISIBILIDAD_TSJ                          939 non-null object
N_REGISTRO_Y_TOMO_CAMARA_2                             939 non-null object
LINK_CAMARA_2                                          935 non-null object
DECISION_DE_FONDO_TSJ                                  936 non-null object
N_REGISTRO_Y_TOMO_TSJ                                  1 non-null object
LINK_TSJ                                               0 non-null float64
RECURSO_EXTRAORDINARIO_Y_RECURRENTE                    0 non-null float64
DECISION_CSJN                                          0 non-null float64
N_REGISTRO_Y_TOMO_CSJN                                 0 non-null float64
LINK_CSJN                                              0 non-null float64
DOCS_ID                                                3393 non-null object
TEXTOS                                                 3320 non-null object
dtypes: float64(6), int64(1), object(57)
memory usage: 1.7+ MB

In [17]:
# see what kind of values each variable has
for col in df.columns:
    print(col)
    print(df[col].unique())
    print('---------')

Unnamed: 0
[   0    1    2 ... 3408 3409 3410]
---------
N
[1.000e+00 2.000e+00 3.000e+00 ... 2.775e+03 2.784e+03 2.785e+03]
---------
NRO_REGISTRO
[nan '600' '601' ... '2883,1' '2891' '2892']
---------
FECHA_RESOLUCION
['1_8_2016' '2_8_2016' '3_8_2016' '4_8_2016' '5_8_2016' '8_8_2016'
 '9_8_2016' '10_8_2016' '12_8_2016' '16_8_2016' '18_8_2016' '19_8_2016'
 '22_8_2016' '23_8_2016' '24_8_2016' '25_8_2016' '26_8_2016' '28_8_2016'
 '29_8_2016' '30_8_2016' '31_8_2016' '1_9_2016' '2_9_2016' '5_9_2016'
 '6_9_2016' '7_9_2016' '8_9_2016' '9_9_2016' '12_9_2016' '13_9_2016'
 '14_9_2016' '16_9_2016' '19_9_2016' '20_9_2016' '21_9_2016' '22_9_2016'
 '26_9_2016' '27_9_2016' '28_9_2016' '30_9_2016' '3_10_2016' '4_10_2016'
 '5_10_2016' '6_10_2016' '7_10_2016' '11_10_2016' '12_10_2016'
 '13_10_2016' '14_10_2016' '17_10_2016' '18_10_2016' '19_10_2016'
 '20_10_2016' '21_10_2016' '24_10_2016' '25_10_2016' '27_10_2016'
 '28_10_2016' '31_10_2016' '1_11_2016' '2_11_2016' '7_11_2016' '8_11_2016'
 '4_11_2016' '11_11_2016' '10_11_2016' '9_11_2016' '14_11_2016'
 '18_11_2016' '21_11_2016' '22_11_2016' '24_11_2016' '25_11_2016'
 '2_12_2016' '12_12_2016' '5_12_2016' '6_12_2016' '7_12_2016' '13_12_2016'
 '15_12_2016' '19_12_2016' '21_12_2016' '26_12_2016' '27_12_2016'
 '29_12_2016' '28_12_2016' '09_01_2017' '12_01_2017' '16_01_2017'
 '17_01_2017' '13_01_2017' '20_01_2017' '19_01_2017' '27_01_2017'
 '31_01_2017' '01_02_2017' '03_02_2017' '02_02_2017' '07_02_2017'
 '06_02_2017' '09_02_2017' '08_02_2017' '10_02_2017' '13_02_2017'
 '14_02_2017' '16_02_2017' '20_02_2017' '22_02_2017' '23_02_2017'
 '21_02_2017' '02_03_2017' '01_03_2017' '03_03_2017' '06_03_2017'
 '07_03_2017' '24_02_2017' '09_03_2017' '10_03_2017' '13_03_2017'
 '15_03_2017' '17_03_2017' '16_03_2017' '20_03_2017' '21_03_2017'
 '22_03_2017' '23_03_2017' '29_03_2017' '28_03_2017' '30_03_2017'
 '27_12_2017' '29_12_2017' '21_12_2017' '26_12_2017' '28_12_2017'
 '31_03_2017' '03_04_2017' '05_04_2017' '04_04_2017' '06_04_2017'
 '07_04_2017' '10_04_2017' '11_04_2017' '12_04_2017' '17_04_2017'
 '18_04_2017' '19_04_2017' '20_04_2017' '21_04_2017' '24_04_2017'
 '25_04_2017' '26_04_2017' '02_05_2017' '28_04_2017' '04_05_2017'
 '03_05_2017' '07_05_2017' '05_05_2017' '08_05_2017' '10_05_2017'
 '09_05_2017' '12_05_2017' '16_05_2017' '17_05_2017' '18_05_2017'
 '19_05_2017' '15_05_2017' '22_05_2017' '23_05_2017' '24_05_2017'
 '26_05_2017' '29_05_2017' '30_05_2017' '31_05_2017' '05_06_2017'
 '02_06_2017' '06_06_2017' '07_06_2017' '09_06_2017' '08_06_2017'
 '12_06_2017' '13_06_2017' '19_06_2017' '21_06_2017' '22_06_2017'
 '27_06_2017' '28_06_2017' '26_06_2017' '29_06_2017' '03_07_2017'
 '04_07_2017' '05_07_2017' '07_07_2017' '10_07_2017' '12_07_2017'
 '30_06_2017' '11_07_2017' '13_07_2017' '14_07_2017' '19_07_2017'
 '31_07_2017' '1_08_2017' '2_08_2017' '4_08_2017' '3_08_2017' '7_08_2017'
 '10_08_2017' '11_08_2017' '09_08_2017' '14_08_17' '14_08_2017'
 '15_08_2017' '18_08_2017' '22_08_2017' '17_08_2017' '23_08_2017'
 '28_08_2017' '29_08_2017' '25_08_2017' '1_09_2017' '4_09_2017'
 '24_08_2017' '6_09_2017' '8_09_2017' '7_09_2017' '5_09_2017' '11_09_2017'
 '12_09_2017' '13_09_2017' '15_09_2017' '14_09_2017' '18_19_2017'
 '19_09_2017' '22_09_2017' '26_09_2017' '27_09_2017' '28_9_2017'
 '29_9_2017' '2_10_2017' '3_10_2017' '4_10_2017' '5_10_2017' '6_10_2017'
 '9_10_2017' '10_10_2017' '11_10_2017' '12_10_2017' '13_10_2017'
 '18_10_2017' '17_10_2017' '20_10_2017' '23_10_2017' '24_10_2017'
 '26_10_2017' '27_10_2017' '31_10_2017' '30_10_2017' '1_11_2017'
 '7_11_2017' '8_11_2017' '9_11_2017' '13_7_2017' '13_11_2017' '10_11_2017'
 '6_11_2017' '15_11_2017' '17_11_2017' '14_11_2017' '21_11_2017'
 '22_11_2017' '23_11_2017' '24_11_2017' '27_11_2017' '28_11_2017'
 '30_11_2017' '29_11_2017' '4_12_2017' '1_12_2017' '5_12_2017'
 '11_12_2017' '7_12_2017' '12_12_2017' '18_12_2017' '19_12_2017'
 '14_12_2017' '20_12_2017' '15_12_2017' '2_01_2018' '3_01_2018'
 '11_1_2018' '12_1_2018' '25_1_2018' '9_01_2018' '12_01_2018' '15_1_2018'
 '16_1_2018' '18_1_2018' '19_01_2018' '18_01_2018' '22_01_2018'
 '23_1_2018' '23_01_2018' '26_01_2018' '30_01_2018' '1_02_2018'
 '2_02_2018' '5_02_2018' '6_02_2018' '07_02_2018' '08_02_2018'
 '09_02_2018' '14_02_2018' '15_02_2018' '16_02_2018' '19_02_2018'
 '20_02_2018' '22_02_2018' '21_02_2018' '28_02_18' '23_02_2018'
 '26_02_2018' '27_02_2018' '28_02_2018' '1_03_2018' '2_03_2018'
 '5_03_2018' '6_03_2018' '7_03_2018' '8_03_2018' '9_03_2018' '13_03_2018'
 '14_03_2018' '15_03_2018' '16_03_2018' '19_03_2018' '20_03_2018'
 '21_03_2018' '22_03_2018' '26_03_2018' '4_04_2018' '5_04_2018'
 '6_04_2018' '10_04_2018' '11_04_2018' '16_04_2018' '17_04_2018'
 '18_04_2018' '19_04_2018' '20_04_2018' '23_04_2018' '24_04_2018'
 '25_04_2018' '26_04_2018' '27_04_2018' '1_05_2018' '2_05_2018'
 '3_05_2018' '4_05_2018' '7_05_2018' '8_05_2018' '9_05_2018' '10_05_2018'
 '11_05_2018' '14_05_2018' '15_05_2018' '16_05_2018' '17_05_2018'
 '18_05_2018' '21_05_2018' '22_05_2018' '23_05_2018' '28_05_2018'
 '29_05_2018' '30_05_2018' '31_05_2018' '1_06_2018' '4_06_2018'
 '5_06_2018' '6_06_2018' '7_06_2018' '8_6_2018' '11_6_2018' '12_6_2018'
 '13_6_2018' '14_6_2018' '15_6_2018' '18_6_2018' '19_6_2018' '21_6_2018'
 '22_6_2018' '25_6_2018' '27_6_2018' '28_06_2018' '29_06_2018' '2_07_2018'
 '3_07_2018' '5_07_2018' '6_07_2018' '10_07_2018' '11_07_2018'
 '12_07_2018' '13_07_2018' '18_07_2018' '19_07_2018' '20_07_2018'
 '25_07_2018' '26_07_2018' '31_07_2018' '1_08_2018' '2_08_2018'
 '3_08_2018' '6_08_2018' '8_08_2018' '9_08_2018' '10_08_2018' '13_08_2018'
 '14_08_2018' '15_08_2018' '16_08_2018' '17_08_2018' '21_08_2018'
 '23_08_2018' '24_08_2018' '27_08_2018' '29_08_2018' '30_08_2018'
 '31_08_2018' '3_09_2018' '4_09_2018' '5_09_2018' '04_09_2018' '06_09_18'
 '06_09_2018' '10_09_2018' '11_09_2018' '12_09_2018' '13_09_2018'
 '14_09_2018' '17_09_2018' '18_09_2018' '19_09_2018' '20_09_2018'
 '21_09_2018' '24_09_2018' '25_09_2018' '26_09_2018' '27_09_2018'
 '28_09_2018' '01_10_2018' '02_10_2018' '03_10_2018' '04_10_2018'
 '05_10_2018' '08_10_2018' '09_10_2018' '10_10_2018' '11_10_2018'
 '12_10_2018' '16_10_2018' '17_10_2018' '18_10_2018' '19_10_2018'
 '22_10_2018' '23_10_2018' '24_10_2018' '25_10_2018' '26_10_2018'
 '29_10_2018' '31_10_2018' '1_11_2018' '2_11_2018' '5_11_2018' '6_11_2018'
 '7_11_2018' '8_11_2018' '9_11_2018' '12_11_2018' '13_11_2018'
 '15_11_2018' '20_11_2018' '21_11_2018' '22_11_2018' '23_11_2018'
 '27_11_2018' '28_11_2018' '29_11_2018' '4_12_2018' '5_12_2018'
 '6_12_2018' '7_12_2018' '10_12_2018' '12_12_2018' '13_12_2018'
 '14_12_2018' '17_12_2018' '18_12_2018' '19_12_2018' '20_12_2018'
 '21_12_2018' '22_12_2018' '26_12_2018' '27_12_2018' '28_12_2018'
 '02_01_2019' '03_01_2019' '04_01_2019' '06_01_2019' '07_01_2019'
 '09_01_2019' '10_01_2019' '11_01_2019' '15_01_2019' '16_01_2019'
 '17_01_2019' '18_01_2019' '21_01_2019' '22_01_2019' '24_01_2019'
 '25_01_2019' '28_01_2019' '30_01_2019' '31_01_2019' '01_02_2019'
 '04_02_2019' '05_02_2019' '06_02_2019' '07_02_2019' '08_02_2019'
 '11_02_2019' '12_02_2019' '13_02_2019' '14_02_2019' '15_02_2019'
 '19_02_2019' '20_02_2019' '21_02_2019' '22_02_2019' '25_02_2019'
 '26_02_2019' '27_02_2019' '28_02_2019' '01_03_2019' '06_03_2019'
 '07_03_2019' '08_03_2019' '11_03_2019' '12_03_2019' '13_03_2019'
 '14_03_2019' '15_03_2019' '18_03_2019' '19_03_2019' '20_03_2019'
 '21_03_2019' '22_03_2019' '25_03_2019' '26_03_2019' '27_03_2019'
 '28_03_2019' '29_03_2019' '01_04_2019' '03_04_2019' '04_04_2019'
 '05_04_2019' '08_04_2019' '09_04_2019' '10_04_2019' '11_04_2019'
 '12_04_2019' '15_04_2019' '16_04_2019' '17_04_2019' '22_04_2019'
 '23_04_2019' '24_04_2019' '25_04_2019' '26_04_2019' '29_04_2019'
 '30_04_2019' '02_05_2019' '03_05_2019' '06_05_2019' '07_05_2019'
 '08_05_2019' '09_05_2019' '13_05_2019' '14_05_2019' '15_05_2019'
 '16_05_2019' '17_05_2019' '20_05_2019' '21_05_2019' '22_05_2019'
 '24_05_2019' '28_05_2019' '23_05_2019' '27_05_2019' '29_05_2019'
 '30_05_2019' '31_05_2019' '02_06_2019' '03_06_2019' '04_06_2019'
 '05_06_2019' '06_06_2019' '07_06_2019' '10_06_2019' '11_06_2019'
 '12_06_2019' '13_06_2019' '14_06_2019' '18_06_2019' '19_06_2019'
 '21_06_2019' '24_06_2019' '25_06_2019' '26_06_2019' '28_06_2019'
 '01_07_2019' '02_07_2019' '03_07_2019' '04_07_2019' '05_07_2019'
 '10_07_2019' '11_07_2019' '12_07_2019' '15_07_2019' '16_07_2019'
 '17_07_2019' '18_07_2019' '19_07_2019' '22_07_2019' '29_07_2019'
 '31_07_2019' '01_08_2019' '02_08_2019' '05_08_2019' '06_08_2019'
 '07_08_2019' '08_08_2019' '12_08_2019' '13_08_2019' '14_08_2019'
 '15_08_2019' '16_08_2019' '20_08_2019' '21_08_2019' '23_08_2019'
 '26_08_2019' '28_08_2019' '29_08_2019' '30_08_2019' '02_09_2019'
 '03_09_2019' '04_09_2019' '05_09_2019' '06_09_2019' '09_09_2019'
 '10_09_2019' '11_09_2019' '12_09_2019' '16_09_2019' '17_09_2019'
 '18_09_2019' '19_09_2019' '20_09_2019' '23_09_2019' '24_09_2019'
 '25_09_2019' '26_09_2019' '27_09_2019' '30_09_2019' '01_10_2019'
 '02_10_2019' '03_10_2019' '04_10_2019' '07_10_2019' '08_10_2019'
 '09_10_2019' '10_10_2019' '11_10_2019' '15_10_2019' '16_10_2019'
 '17_10_2019' '18_10_2019' '21_10_2019' '22_10_2019' '23_10_2019'
 '24_10_2019' '25_10_2019' '28_10_2019' '29_10_2019' '30_10_2019'
 '31_10_2019' '1_11_2019' '4_11_2019' '5_11_2019' '6_11_2019' '7_11_2019'
 '8_11_2019' '11_11_2019' '12_11_2019' '14_11_2019' '19_11_2019'
 '20_11_2019' '21_11_2019' '22_11_2019' '25_11_2019' '26_11_2019'
 '27_11_2019' '28_11_2019' '29_11_2019' '2_12_2019' '3_12_2019'
 '4_12_2019' '5_12_2019' '6_12_2019' '9_12_2019' '10_12_2019' '11_12_2019'
 '13_12_2019' '16_12_2019' '17_12_2019' '18_12_2019' '19_12_2019'
 '20_12_2019' '26_12_2019' '27_12_2019' '07_01_20' '09_01_20' '14_01_20'
 '22_01_20' '24_01_20' '27_01_20' '29_01_20' '30_01_20' '31_01_20'
 '3_02_20' '4_02_20' '5_02_20' '6_02_20' '7_02_20' '10_02_20' '11_02_20'
 '12_02_20' '13_02_20' '14_02_20' '17_02_20' '18_02_20' '19_02_20'
 '20_02_20' '21_02_20' '26_02_20' '27_02_20' '28_02_20' '3_03_20'
 '4_03_20' '5_03_20' '10_03_20' '12_03_20' '13_03_20' '16_03_20'
 '17_03_20' '18_03_20' '19_03_20' '20_03_20' '22_03_20' '26_03_20'
 '27_03_20' '28_03_20' '31_03_20' '2_04_20' '03_04_20' '4_04_20'
 '07_04_20' '16_4_20' '20_4_20' '22_4_20' '23_4_20' '24_4_20' '27_4_20'
 '29_4_20' '30_4_20' '1_5_20' '4_5_20' '6_5_20' '7_5_20' '8_5_20' '9_5_20'
 '10_5_20' '11_5_20' '12_5_20' '13_5_20' '14_5_20' '15_5_20' '18_5_20'
 '19_5_20' '20_5_20' '21_5_20' '22_5_20' '27_5_20' '28_5_20' '29_5_20'
 '1_6_20' '3_6_20' '5_6_20' '8_6_20' '10_6_20' '16_6_20' '17_6_20'
 '18_6_20' '19_6_20' '22_6_20' '23_6_20' '24_6_20' '25_6_20' '26_6_20'
 '29_6_20' '30_6_20' '01_07_20' '02_07_20' '03_07_20' '05_07_20'
 '06_07_20' '07_07_20' '08_07_20' '15_07_20' '16_07_20' '17_07_20'
 '22_07_20' '23_07_20' '24_07_20' '28_07_20' '30_07_20' '2_08_20'
 '4_08_20' '6_08_20' '8_08_20' '9_08_20']
---------
FIRMA
['Pablo_Casas' 'Juez_interinamente_a_cargo' 'juez_interinamente_a_cargo']
---------
MATERIA
['penal' 'contravencional' 'faltas' 'allanamiento_autonomo'
 'ejecucion_de_multa' 'amparo' 'habeas_corpus']
---------
ART_INFRINGIDO
['1' '149bis' '52' '73' '128' '111' '181_inc1' '6' '79' '2.1.1' '131'
 '189bis' '9.1.1' '85' '4.1.1.2' '83' '183' '82' '2.1.15' '96' '6.1.9'
 '116' '6.1.28' '6.1.40' '54' '150' '2.2.14' nan '104' '23' '74' '6.1.63'
 '58' '93' '6.1.52' '4.1.22' '193bis' '184_inc5' '80' '11.1.2' '103'
 '6.1.2' '92' '153bis' '301bis' '129' '53_inc5' '295' '186' '3' '106'
 '6.1.26' '114' '95' '65bis' '86' '1.1.6' '125bis' '88' '98' '108' '57'
 '101' '97' '81' '56' '4.1.1' '1.3.22' '2.1.19' '164' '2.1.3' '168'
 '4.1.24' '239' '4.1.17' '1.3.31' '89' '2.2.1' '273' '10.1.5' '238'
 '53_inc3' '292_parr2' '72' '118' '249' '77' '248' '266' '6.1.12'
 '149bis_129' '6.1.49' '6.1.4' '119' '6.1.54' '6.1.42' '162' '258' '76'
 '100' '90' '149bis_parr2' '149ter_inc2b)' '5c' '6.1.12.1' '173_inc2'
 '4.1.7' '181_inc3' '6.1.31' '94' '67bis' '107' '292_parr1' '129_parr2'
 '14' '153bis_parr2' '6.1.24' '80_inc2' '186_inc4' '84' '109' '135'
 '2.1.21' '289_inc3' '51' '243' '141' '6.1.94' '5e' '296' '277_inc_d'
 '2.1.16' '163_inc4' '3.1.1' '71bis' '6.1.44' '6.1.67' '1.3.3' '17' '87'
 '186_inc5' '6.1.41' '148bis' '1.3.6.1' '120' '94bis' '59' '1.3.20'
 '11.1.4' '6.1.8' '163' '6.1.37' '2.1.17' '208' '105' '186_inc1' '174'
 '113']
---------
CODIGO_O_LEY
['ley_14346' 'codigo_penal_de_la_nacion' 'codigo_contravencional'
 'ley_26735' 'ley_451' 'ley_13944' nan 'ley_1217' 'ley_24270' 'ley_23592'
 'ley_23737' 'ley_23098' 'ley_12331']
---------
CONDUCTA
['proteccion_animal' 'amenazas' 'hostigamiento' 'incumplir_clausura'
 'mesnna_masnna'
 'conducir_con_mayor_grado_de_alcohol_o_bajo_efectos_de_estupefacientes'
 'usurpacion' 'apropiacion_indebida_de_tributos'
 'cuidar_coches_sin_autorizacion'
 'elementos_de_prevencion_contra_incendio'
 'contactar_menor_por_medio_de_tecnologias_para_cometer_delitos_contra_su_integridad_sexual'
 'tenencia_de_arma' 'obstruccion_de_inspeccion'
 'portar_armas_no_convencionales' 'habilitacion_en_infraccion'
 'ruidos_molestos' 'incumplimiento_deberes_familiares' 'daños'
 'uso_indebido_del_espacio_publico' 'zanjas_y_pozos_en_via_publica'
 'lesiones' 'placas_de_dominio' 'juego_sin_autorizacion'
 'exceso_de_velocidad' 'no_respetar_senda_peatonal'
 'arrojar_sustancias_insalubres_en_lugares_publicos'
 'ingreso_a_domicilio_sin_autorizacion' 'portacion_de_arma'
 'sancion_generica' 'allanamiento_autonomo' 'Hostigamiento'
 'abuso_de_armas' 'ejecucion_de_multa' 'amparo'
 'ejercer_ilegitimamente_una_actividad' 'cruce_de_semaforo_en_rojo'
 'ingresar_contra_derecho_admision' 'ingresar_sin_entrada'
 'estacionamiento_prohibido' 'exhibicion_de_documentacion_obligatoria'
 'delito_contra_seguridad_transito' 'ensuciar_bienes'
 'servicios_de_seguridad_requisitos_incumplidos'
 'arrojar_cosas_que_puedan_causar_lesiones' 'licencia_vencida'
 'acceso_a_sistema_restringido' 'juegos_de_azar_sin_autorizacion'
 'organizar_sin_autorizacion_juego' 'exhibiciones_obscenas'
 'falsificacion_certificado_medico' 'incendios_y_otros_estragos'
 'impedimento_de_contacto_de_menor_con_padre_no_conviviente'
 'propaganda_discriminatoria' 'abandono_de_personas'
 'conducir_usando_aparato_electronico' 'acoso_sexual_callejero'
 'documentacion_sanitaria'
 'promocion_o_facilitacion_de_prostitucion_de_personas'
 'omitir_recaudos_de_organizacion' 'ingresar_artefactos_pirotecnicos'
 'obstaculizar_ingreso_o_salida' 'afectar_el_desarrollo_del_espectaculo'
 'suministrar_bebidas_alcoholicas' 'revender_entradas'
 'acceder_a_lugares_distintos_segun_entrada' 'obstruccion_de_via_publica'
 'espantar_animales' 'ausencia_de_habilitacion'
 'desinfeccion_y_desratizacion' 'incumplimiento_perimetro_profundidad'
 'robo' 'exceso_capacidad_ingreso' 'extorsion'
 'obligacion_de_exhibir_cartel' 'desobediencia_a_la_autoridad'
 'venta_o_consumo_de_bebidas_alcoholicas_fuera_del_horario'
 'vehiculo_abandonado' 'permiso_y_planos_de_obra' 'denegacion_de_justicia'
 'placas_de_Dominio'
 'falsedad_documental_de_certificado_de_aptitud_Ambiental'
 'atentado_contra_la_autoridad' 'falsificacion_de_documento'
 'afectar_servicios_de_emergencia_o_seguridad'
 'incumplimiento_deberes_funcionario_publico' 'obstruccion_via_publica'
 'coimas' 'verificacion_tecnica'
 'arrojar_cosas_que_Puedan_causar_lesiones'
 'transporte_de_pasajeros_sin_habilitacion'
 'conducir_sin_licencia_que_lo_habilite_por_categoria_de_vehiculo'
 'abuso_sexual' 'estacionamiento_sobre_senda_peatonal'
 'circular_por_lugar_prohibido' 'hurto' 'cohecho_activo' 'estupefacientes'
 'no_realizar_grabado_de_autopartes' 'retencion_indebida'
 'taxis_transportes_escolares_remises_sin_autorizacion'
 'no_respetar_carriles' 'maltrato' 'administracion_fraudulenta'
 'espejos_retrovisores' 'homicidio' 'habeas_corpus'
 'exhortos_de_otras_jurisdicciones' 'incumplimiento_de_plazos'
 'cierre_defectuoso'
 'falsificacion_de_numeracion_de_objeto_registrada_de_acuerdo_a_ley'
 'apariencia_falsa_para_entrar_a_domicilio_o_lugar_privado'
 'pelear_en_lugar_publico'
 'abuso_de_autoridad_e_incumplimiento_deberes_funcionario_publico'
 'incitar_al_desorden' 'desobediencia_a_cargas_procesales'
 'privacion_ilegitima_de_la_libertad'
 'transporte_de_pasajeros_sin_habilitacion_o_autorizacion'
 'uso_de_documento_falso_o_adulterado' 'encubrimiento'
 'mantenimiento_de_cercas_y_aceras' 'hurto_con_escalamiento'
 'publicidad_en_lugares_no_habilitados_via_publica'
 'difusion_no_autorizada_de_imagenes_intimas' 'transporte_de_pasajeros'
 'uso_o_exhibicion_de_franquicias' 'ruidos_y_vibraciones'
 'regentear_o_administrar_casas_de_tolerancia'
 'circular_por_carriles_exclusivos' 'explotacion_trabajo_infantil'
 'obligacion_de_informar_prohibicion_de_fumar'
 'incumplir_obligaciones_legales' 'derecho_admision' 'residuos_peligrosos'
 'servicios_de_seguridad_prohibiciones_incumplidas'
 'falta_de_poliza_de_seguros' 'obstruccion_de_via'
 'ejercicio_ilegal_de_la_medicina'
 'incendio_explosion_inundacion_con_peligro_para_bienes'
 'defraudación_contra_la_administracion_publica']
---------
CONDUCTA_DESCRIPCION
['simples' 'agravado_violencia_de_genero' nan 'por_despojo'
 'de_fuego_uso_civil' 'agravadas_por_uso_de_armas' 'en_riña' 'coactivas'
 'agravados' 'agravado_menor_de_edad' 'leves_agravadas' 'simple' 'leves'
 'destinado_a_acreditar_identidad_de_personas_habilitacion_o_titularidad'
 'de_guerra' 'tentativa' 'coactivas_agravadas' 'agravado'
 'para_produccion_o_tenencia_con_fines_de_comercializacion'
 'por_turbacion_de_la_posesion' 'culposas'
 'agravadas_por_uso_de_armas_impropia' 'agravado_por_el_vinculo'
 'publico_o_privado' 'agravadas_por_edad' 'tenencia'
 'tentativa_agravado_alevosia' 'agravado_peligro_de_muerte'
 'graves_tentativa' 'entrega_suministro_facilitacion'
 'coactivas_agravadas_por_uso_de_armas' 'graves' 'seguido_de_muerte'
 'conduccion_imprudente']
---------
VIOLENCIA_DE_GENERO
['no' 'si']
---------
V_FISICA
['no_corresponde' 'no' 'si' 's/d']
---------
V_PSIC
['no_corresponde' 'si' 'no' 's/d']
---------
V_ECON
['no_corresponde' 'no' 'si' 's/d']
---------
V_SEX
['no_corresponde' 'no' 'si' 's/d']
---------
V_SOC
['no_corresponde' 'no' 'si' 's/d']
---------
V_AMB
['no_corresponde' 'no' 'si' 's/d']
---------
V_SIMB
['no_corresponde' 'si' 'no' 's/d']
---------
FRASES_AGRESION
['no_corresponde' 'me la vas a pagar' nan 'ya los voy a matar'
 'te voy a matar'
 'no me importa nada_ te voy a matar_ puta de mierda_ trola_ te voy a arruinar_ muerto o preso no me importa_ no te mereces a mi hijo'
 'si no estas conmigo no vas a ser feliz con nadie_ sos una fracasada_ con razon te metieron los cuernos _ seguis tratandome mal _ yo que te ame como nadie te amara jamas _ muchos me decian que eras una putita egoista y yo te defendia _ soy demasiado para vos'
 'gorda hija de puta andate de aca_ no te quiero ni ver aca hija de puta _ te voy a matar _ estas loca'
 'les voy a pegar un tiro' 'te voy a incendiar con vos adentro'
 'vecino de mierda los voy a matar' 'te voy a matar hija de puta'
 'hija de puta_mañana no vas a estar viva'
 'no vas a salir viva de aca_te voy a matar_a mi hijo tambien lo voy a matar'
 'se mueren la semana que viene el y vos'
 'trola_ya no te voy a escribir mas_andate a la concha de tu madre'
 'mi hija es todo_todo lo que no vas a volver a ver jamas'
 'hija de mil puta_te voy a sacar a la nena_te voy a echar a la mierda_te voy a matar'
 'con mi plata hago lo que quiero'
 'si no sacas esa foto te voy a cortar el cuello'
 'este celular se rompe aca'
 'gorda hija de puta andate de aca_no te quiero ni ver aca hija de puta_te voy a matar_estas loca'
 'sos una putita_sos rapida' 'te voy a prender fuego'
 'te voy a prender fuego_hija de puta'
 'te voy a matar a vos y a tus hijos'
 'te voy a pasar por encima con el auto_te voy a matar'
 'puta_hija de puta_nefasta'
 'me la vas a pagar_te voy a buscar_te voy a encontrar'
 'si no te vas de la casa te va a pasar algo malo'
 'andate a dormir_te voy a matar_te voy a cagar a palos'
 'basura_anda a trabajar o a revolear la cartera'
 'la vas a pagar_vas a llorar_no me dejas otra opcion_si no me contestas voy a ir a casa_ ya vas a ver'

In [61]:
#the following columns looked interesting in my evaluation, so I am gonna take a closer look at them
cols = ['MATERIA','TEXTOS','VIOLENCIA_DE_GENERO',
        'V_FISICA','V_PSIC','V_ECON','V_SEX','V_SOC','V_AMB','V_SIMB',
        'GENERO_ACUSADO/A','EDAD_ACUSADO/A AL MOMENTO DEL HECHO','EDAD_DENUNCIANTE_AL_MOMENTO_DEL_HECHO',
        'LUGAR_DEL_HECHO\n']

In [62]:
df[cols]

,MATERIA,TEXTOS,VIOLENCIA_DE_GENERO,V_FISICA,V_PSIC,V_ECON,V_SEX,V_SOC,V_AMB,V_SIMB,GENERO_ACUSADO/A,EDAD_ACUSADO/A AL MOMENTO DEL HECHO,EDAD_DENUNCIANTE_AL_MOMENTO_DEL_HECHO,LUGAR_DEL_HECHO\n
0,penal,'U\n\n� Poder Judicial de la Ciudad de Buenos ...,no,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,usuario_de_facebook,no_corresponde,no_corresponde,no_corresponde
1,penal,� Poder Judicial de la Ciudad de Buenos Aires\...,si,no,si,no,no,no,no,si,masculino,17,17,en_domicilio_particular
2,contravencional,'o\n·\n\nPoder Judicial de la Ciudad de Buenos...,si,si,si,si,no,no,no,si,masculino,50,23,en_domicilio_particular
3,contravencional,� Poder Judicial de la Ciudad de Buenos Aires\...,no,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,persona_juridica,no_corresponde,no_corresponde,no_corresponde
4,penal,"""\n\n_.¡\n\n�s\n�li.2l!l\n\n� Poder Judicial d...",si,no,si,si,no,si,no,si,masculino,34,s/d,s/d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3388,penal,RESOLUCIÓN INTERLOCUTORIA\nHace lugar a las me...,si,si,si,no,no,no,no,si,masculino,6/02/1900,s/d,NaN
3389,penal,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...,no,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,masculino,28/01/1900,no_corresponde,NaN
3390,penal,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...,no,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,masculino,28/01/1900,no_corresponde,NaN
3391,penal,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...,no,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,no_corresponde,masculino,28/01/1900,no_corresponde,NaN
3392,penal,AUDIENCIA DE PRISIÓN PREVENTIVA\n(Art. 173 CPP...,si,si,si,no,no,no,no,no,masculino,13/02/1900,17/03/1900,NaN

In [63]:
df[cols].isnull().mean()

MATERIA                                  0.000000
TEXTOS                                   0.021515
VIOLENCIA_DE_GENERO                      0.000000
V_FISICA                                 0.000000
V_PSIC                                   0.000000
V_ECON                                   0.000000
V_SEX                                    0.000000
V_SOC                                    0.000000
V_AMB                                    0.000000
V_SIMB                                   0.000000
GENERO_ACUSADO/A                         0.000589
EDAD_ACUSADO/A AL MOMENTO DEL HECHO      0.002063
EDAD_DENUNCIANTE_AL_MOMENTO_DEL_HECHO    0.003537
LUGAR_DEL_HECHO\n                        0.007663
dtype: float64

In [36]:
pd.crosstab(df.VIOLENCIA_DE_GENERO,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
VIOLENCIA_DE_GENERO,,,,,,,,
no,12,8,1057,3,366,2,1049,2497
si,0,0,196,0,0,0,700,896
All,12,8,1253,3,366,2,1749,3393

In [37]:
pd.crosstab(df.V_FISICA,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_FISICA,,,,,,,,
no,0,0,108,0,0,0,314,422
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,2,2
si,0,0,88,0,0,0,388,476
All,12,8,1253,3,366,2,1749,3393

In [38]:
pd.crosstab(df.V_AMB,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_AMB,,,,,,,,
no,0,0,181,0,0,0,632,813
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,15,0,0,0,69,84
All,12,8,1253,3,366,2,1749,3393

In [39]:
pd.crosstab(df.V_ECON,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_ECON,,,,,,,,
no,0,0,171,0,0,0,528,699
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,25,0,0,0,173,198
All,12,8,1253,3,366,2,1749,3393

In [40]:
pd.crosstab(df.V_PSIC,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_PSIC,,,,,,,,
no,0,0,7,0,0,0,79,86
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,189,0,0,0,622,811
All,12,8,1253,3,366,2,1749,3393

In [41]:
pd.crosstab(df.V_SEX,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_SEX,,,,,,,,
no,0,0,180,0,0,0,648,828
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,16,0,0,0,53,69
All,12,8,1253,3,366,2,1749,3393

In [42]:
pd.crosstab(df.V_SIMB,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_SIMB,,,,,,,,
no,0,0,9,0,0,0,73,82
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,187,0,0,0,628,815
All,12,8,1253,3,366,2,1749,3393

In [43]:
pd.crosstab(df.V_SOC,df.MATERIA,margins=True)

MATERIA,allanamiento_autonomo,amparo,contravencional,ejecucion_de_multa,faltas,habeas_corpus,penal,All
V_SOC,,,,,,,,
no,0,0,169,0,0,0,578,747
no_corresponde,12,8,1057,3,366,2,1045,2493
s/d,0,0,0,0,0,0,3,3
si,0,0,27,0,0,0,123,150
All,12,8,1253,3,366,2,1749,3393

In [47]:
pd.crosstab(df.VIOLENCIA_DE_GENERO,df['GENERO_ACUSADO/A'],margins=True)

GENERO_ACUSADO/A,femenino,lgbtiq+,manifestantes,masculino,nn,no_corresponde,organo_jurisdiccional,pagina_web,persona_juridica,personal_policial,...,usuario_de_cuenta_de_google,usuario_de_facebook,usuario_de_imgur,usuario_de_instagram,usuario_de_mercado_libre,usuario_de_skout,usuario_de_skype,usuario_de_twitter,usuario_de_youtube,All
VIOLENCIA_DE_GENERO,,,,,,,,,,,,,,,,,,,,,
no,325,4,1,1793,25,12,1,10,108,2,...,19,125,1,17,5,3,11,27,2,2495
si,0,0,0,896,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,896
All,325,4,1,2689,25,12,1,10,108,2,...,19,125,1,17,5,3,11,27,2,3391

In [52]:
for col in cols:
    print(df[col].value_counts())

870.0     8
1496.0    8
792.0     6
2048.0    6
2393.0    5
         ..
141.0     1
1029.0    1
2715.0    1
2698.0    1
1.0       1
Name: N, Length: 2767, dtype: int64
penal                    1749
contravencional          1253
faltas                    366
allanamiento_autonomo      12
amparo                      8
ejecucion_de_multa          3
habeas_corpus               2
Name: MATERIA, dtype: int64
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               31
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              27